name: Checkstyle

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Checkstyle JAR
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.17.0/checkstyle-10.17.0-all.jar -O checkstyle-10.17.0-all.jar

      - name: Run Checkstyle
        run: |
          java -jar checkstyle-10.17.0-all.jar \
          -c checkstyle.xml \
          -o checkstyle-report.xml \
          .
        continue-on-error: true
